#ifndef __PICOK7_H__

#define __PICOK7_H__


#ifdef LIB_PICO_STDIO_USB
#define prtdbg(...) printf(__VA_ARGS__)
#else
#define prtdbg(...)
#endif


// Hardware connections
//---------------------------

#define PIN_ENC_SW  4
#define PIN_ENC_DT  5
#define PIN_ENC_CLK 6

#define ENC_PIO      pio1

#define LCD_pinCS   28
#define LCD_pinRES  27
#define LCD_pinRS   26
#define LCD_pinSCL  14
#define LCD_pinSI   15
#define LCD_SPI     spi1

#define PIN_WS2812  16

#define WS2812_PIO  pio0

#define PIN_EAR     29
#define K7_PIO      pio0


// "Keys" (generated by encoder)
//---------------------------
#define KEY_ENTER 0
#define KEY_UP    1
#define KEY_DN    2

// Public functions
//---------------------------

// Encoder
void encoderInit (PIO pio, uint pin_a, uint pin_b, uint pin_sw);
int  getKey (void);

// Tape
void k7Init (PIO pio, uint pin);
bool k7Send (char *pfile);

// Display
void displayInit (void);
void displayClear (void);
void displayStr (char *str, int l, int c, bool inverse);
int displayMenu (int lt, int nl, int nopc, char *opc[]);

// WS2812 RGB LED
void ws282Init (PIO pio, uint pin);
void ws2812Update(uint32_t pixel);
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return
            ((uint32_t) (r) << 16) |
            ((uint32_t) (g) << 24) |
            ((uint32_t) (b) << 8);
}


#endif
